name: Benchmark Skywalking-java
on:
  workflow_dispatch:
  schedule: 
    - cron: "0 3 * * 1"


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Performance measurement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '3.5.3'
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Execute MooBench Benchmark
        run: |
          ./setup.sh
          cd frameworks/Skywalking-java/
          export MOOBENCH_CONFIGURATIONS="0 1 2 3"
          export NUM_OF_LOOPS=3
          ./benchmark.sh 
          cd results-Skywalking-java
          unzip results.zip
          pwd
          ls
          ../../../analysis/getGHActionsFormat.sh &> output.json
          cat output.json
          mv output.json ../../../
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 'Skywalking-java'
          tool: 'customSmallerIsBetter'
          output-file-path: output.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
