name: Benchmark Kieker-java (4 Threads)
on:
  workflow_dispatch:
  push:
    branches: [ main, continuous-gh-benchmarks ]
  schedule: 
    - cron: "0 3 * * *"


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Performance measurement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Execute MooBench Benchmark
        run: |
          ./setup.sh
          cd frameworks/Kieker-java/
          export THREADS=4
          export NUM_OF_LOOPS=10 
          export MOOBENCH_CONFIGURATIONS="0 1 2 4"
          ./benchmark.sh 
          cd results-Kieker-java
          unzip results.zip 
          ../../../analysis/getGHActionsFormat.sh &> output.json
          cat output.json
          mv output.json ../../../
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 'Kieker-java-4'
          tool: 'customSmallerIsBetter'
          output-file-path: output.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
